DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ele}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ell_}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ell*}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ellæ}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ell@}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{elle}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{elli}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ellu}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ellx}';
DELETE FROM pronouns WHERE language = 'spa' AND cases = '{ol, olles}';
